From harness/ubi:safe-ubi8.5

COPY --chown=65534:65534 keystore.jks /opt/harness/
COPY --chown=65534:65534 verification-config.yml /opt/harness/
COPY --chown=65534:65534 verification-capsule.jar /opt/harness/
COPY --chown=65534:65534 scripts /opt/harness/

RUN  chmod 500 /opt/harness/*.sh

CMD [ "./run.sh" ]
