FROM redhat/ubi8-minimal:8.4

COPY --chown=65534:65534 alpn-boot-8.1.13.v20181017.jar /opt/harness/
COPY --chown=65534:65534 redisson-jcache.yaml /opt/harness/
COPY --chown=65534:65534 config.yml /opt/harness/
COPY --chown=65534:65534 classpath_metadata.json /opt/harness/
COPY --chown=65534:65534 pipeline-service-capsule.jar /opt/harness/
COPY --chown=65534:65534 scripts /opt/harness/

RUN chmod 500 /opt/harness/*.sh

CMD [ "./run.sh" ]
