FROM registry.access.redhat.com/ubi8/ubi-minimal:8.5

RUN microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y java-11-openjdk-devel \
            && microdnf --setopt=install_weak_deps=0 --setopt=tsflags=nodocs install -y shadow-utils \
            && microdnf install wget \
            && microdnf update -y \
            && microdnf clean all \
            && rpm -q java-11-openjdk-devel shadow-utils \
            && wget https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64 -O /usr/bin/yq \
            && chmod +x /usr/bin/yq \
            && microdnf remove wget
ENV \
            JAVA_HOME="/usr/lib/jvm/java-11" \
            JAVA_VENDOR="openjdk" \
            JAVA_VERSION="11"


RUN mkdir -p /opt/harness/plugins \
    && chown -R 65534:65534 /opt/harness \
    && chmod -R 700 /opt/harness


WORKDIR /opt/harness

USER 65534