FROM harness/manager-openjdk-8u242:x86_64-alpine-jdk8u242-b08

COPY --chown=65534:65534 alpn-boot-8.1.13.v20181017.jar /opt/harness/
COPY --chown=65534:65534 keystore.jks /opt/harness/
COPY --chown=65534:65534 newrelic.yml /opt/harness/
COPY --chown=65534:65534 hazelcast.xml /opt/harness/
COPY --chown=65534:65534 redisson-jcache.yaml /opt/harness/
COPY --chown=65534:65534 config.yml /opt/harness/
COPY --chown=65534:65534 classpath_metadata.json /opt/harness/
COPY --chown=65534:65534 rest-capsule.jar /opt/harness/
COPY --chown=65534:65534 scripts /opt/harness/

RUN set -x \
    && wget https://github.com/inspectIT/inspectit-ocelot/releases/download/1.16.0/inspectit-ocelot-agent-1.16.0.jar -O /opt/harness/inspectit-ocelot-agent-1.16.0.jar \
    && chmod +x /opt/harness/inspectit-ocelot-agent-1.16.0.jar

RUN chmod 500 /opt/harness/*.sh

CMD [ "./run.sh" ]
